#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh" # Comentado

echo "Running commit-msg hook..."

# Usar npx en lugar de bunx para ejecutar commitlint
npx commitlint --edit $1

# Capturar el código de salida
exitCode=$?

if [ $exitCode -ne 0 ]; then
  echo "Husky > commit-msg hook failed (npx commitlint exited con código $exitCode)." >&2
else
  echo "Husky > commit-msg hook passed (npx commitlint)."
fi

exit $exitCode
