name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-format-types:
    name: Lint, Format & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.11'

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun run format:check

      - name: Run linting
        run: bun run lint

      - name: Type check
        run: bun run type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.11'

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
